# Generated by Django 5.2.4 on 2025-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contactmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
    ]
