# Generated by Django 5.2.4 on 2025-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=50)),
                ('sowing_season', models.CharField(max_length=50)),
                ('harvest_season', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('ideal_temperature_min', models.FloatField()),
                ('ideal_temperature_max', models.FloatField()),
                ('ideal_rainfall', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
                ('germination', models.CharField(max_length=50)),
                ('vegetative_growth', models.CharField(max_length=50)),
                ('flowering', models.CharField(max_length=50)),
                ('maturity', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
