# Generated by Django 5.2.4 on 2025-07-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('crop_name', models.CharField(max_length=100)),
                ('stage_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('water_supply_duration', models.CharField(max_length=50)),
            ],
        ),
    ]
