# Generated by Django 5.2.4 on 2025-07-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_growthstage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthstage',
            old_name='end_date',
            new_name='flowering_end',
        ),
        migrations.RemoveField(
            model_name='growthstage',
            name='stage_name',
        ),
        migrations.RemoveField(
            model_name='growthstage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='growthstage',
            name='water_supply_duration',
        ),
        migrations.AddField(
            model_name='growthstage',
            name='flowering_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='flowering_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='germination_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='germination_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='germination_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='maturity_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='maturity_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='maturity_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='vegetative_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='vegetative_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='vegetative_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
