# Generated by Django 5.2.4 on 2025-07-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_rename_end_date_growthstage_flowering_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='flowering_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='germination_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='maturity_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='vegetative_water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
