# Generated by Django 5.2.4 on 2025-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=50)),
                ('application_rate', models.IntegerField()),
                ('toxicity', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('usage_frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
