# Generated by Django 5.2.4 on 2025-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('cause', models.CharField(max_length=255)),
                ('control_measures', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
