# Generated by Django 5.2.4 on 2025-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide', '0002_cropdisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('fertilizer_type', models.CharField(max_length=50)),
                ('composition', models.CharField(max_length=100)),
                ('application_method', models.CharField(max_length=100)),
                ('application_time', models.CharField(max_length=100)),
            ],
        ),
    ]
